name: flutter_uploader_example
version: 3.0.0-beta.3
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.3
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.4

dev_dependencies:
  flutter_lints: ^1.0.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_uploader:
    path: ../

flutter:
  uses-material-design: true
