name: flutter_uploader
description: A plugin for creating and managing upload tasks with optional background exection support.
version: 3.0.0-beta.4
homepage: https://github.com/fluttercommunity/flutter_uploader
maintainer: Sebastian Roth (@ened)

environment:
  sdk: ^3.5.3
  flutter: ">=1.20.0"

dependencies:
  equatable: ^2.0.3
  file_picker: ^8.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  mockito: ^5.0.17
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bluechilli.flutteruploader
        pluginClass: FlutterUploaderPlugin
      ios:
        pluginClass: FlutterUploaderPlugin

false_secrets:
  - example/ios/Runner/GoogleService-Info.plist
